workflows:
  android-release:
    name: Cutepanda Android Build
    instance_type: mac_mini_m2

    environment:
      node: 22
      java: 21
      android_signing:
        - keystore_reference

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Generate Icons and Splash Screens
        script: npx @capacitor/assets generate --android

      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Sync Capacitor
        script: npx cap sync android

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
